### ISSUE TITLE
ESP32 Wrong output

### ISSUE THREAD

**Issue by ripper121** [PaulStoffregen/PS2Keyboard#14]
With the ESP32 I got some wrong output.
When i press the same button on the keyboard sometimes another letter will appear on the Serial Output.

**Comment by PaulStoffregen** [comment]
I do not directly support any ESP.  I depend on the ESP community to resolve any ESP problem and submit pull requests.

Please, do not post again here.  Ask on the ESP forum for help.  Only post here when people on from the ESP community have fully diagnosed the problem.
