### ISSUE TITLE
ESP8266 and CORE_INT_EVERY_PIN

### ISSUE THREAD

**Issue by jscrane** [PaulStoffregen/PS2Keyboard#20]
### Description

ESP8266 is only supported when ARDUINO_ESP8266_NODEMCU is defined. This isn't the case for, e.g., Wemos Mini D1.

### Steps To Reproduce Problem

Run Simple_Test example on Wemos Mini D1. It doesn't work. Change utility/int_pins.h as follows and it works:

```
-#elif defined(ARDUINO_ESP8266_NODEMCU)
+#elif defined(ESP8266)
```

### Hardware & Software

Board Wemos Mini D1
Shields / modules used none
Arduino IDE version 1.8.4
Teensyduino version (if using Teensy) N/A
Version info & package name (from Tools > Boards > Board Manager) esp8266-arduino v2.4.2
Operating system & version Linux Mint Debian Edition
Any other software or hardware?

### Arduino Sketch

examples/Simple_Test.ino

### Errors or Incorrect Output

See above.

**Comment by RickeyWard** [comment]
I can confirm, it does work on the wemos D1 mini with this change

**Comment by PaulStoffregen** [comment]
Ok, done.
