### ISSUE TITLE
error: narrowing conversion

### ISSUE THREAD

**Issue by himijendrix24** [PaulStoffregen/PS2Keyboard#22]
Example files don't compile.
Using Arduino IDE 1.8.6

```
C:\Users\Justus\Documents\Arduino\libraries\PS2Keyboard\PS2Keyboard.cpp:271:1: error: narrowing conversion of '-15708' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]

 };

 ^
```

**Comment by PaulStoffregen** [comment]
Upgrade to newer Arduino.  In using a non-AVR board, also use the boards manager to update your board's support files.

This problem was fixed on Teensy and most Arduino boards quite some time ago.  You simply have older software, before the fix.

**Comment by himijendrix24** [comment]
Thanks, works.
It's now a warning instead of an error.
