### ISSUE TITLE
Wrong handling of altgr keymaps

### ISSUE THREAD

**Issue by slviajero** [PaulStoffregen/PS2Keyboard#38]
There seems to be a bug in the library in handling of altgr on systems that use progmem. The altgr part of the keymap doesn't work in German. 

Looking at the code in line 489 the reason is clear:

'			} else if ((state & ALTGR) && keymap->uses_altgr) {'

tries to access keymap->usess_altgr in PROGMEM without properly accessing it through the function pgm_read_byte(). The code line should read

'                        } else if ((state & ALTGR)  && pgm_read_byte(keymap->uses_altgr) ) {'

instead. This works flawlessly.

**Comment by PaulStoffregen** [comment]
fixed https://github.com/PaulStoffregen/PS2Keyboard/commit/1cb0eee31b57711f86e0da251999b712abb607c1
