### ISSUE TITLE
ThIS IS more A reQuest

### ISSUE THREAD

**Issue by fredericplante** [PaulStoffregen/PS2Keyboard#8]
Would IT bE possiBLE to ToGGLe on and Off THe LockS KEys AND Leds Using THIs liBRarY?

**Comment by PaulStoffregen** [comment]
Please post this question on the forum.

http://forum.pjrc.com/forums/2-Project-Guidance

I write detailed tech answers on the forum, so the info becomes a searchable public knowledge base.

Github issues are for reporting specific software problems.  This is simply the wrong place to ask for project guidance.
